name: fluetooth_example
description: Demonstrates how to use the fluetooth plugin.

publish_to: 'none' 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  esc_pos_gen: ^3.2.0
  flutter:
    sdk: flutter

  fluetooth:
    path: ../
  image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
