name: fluetooth
description: Flutter library for sending bytes to Bluetooth devices.
version: 0.0.4
repository: https://www.github.com/iandis/fluetooth
issue_tracker: https://www.github.com/iandis/fluetooth/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  
  plugin:
    platforms:
      android:
        package: app.iandis.fluetooth
        pluginClass: FluetoothPlugin
      ios:
        pluginClass: FluetoothPlugin
